#!/bin/bash

set -e

source "$(dirname "$0")/common"

cd "$(dirname "$0")/.."

_check_dependencies

case "$1" in
  door_sensor)
    echo "Deploying lua build for door_sensor..."
    for file in ./door_sensor/**
    do
      _esp_wipe

      sleep 2 # Ensure wipe took effect

      cmd="luatool.py -p $ESP8266_PORT -b $BAUD_RATE -f ${file}"
      echo $cmd
      eval $cmd
    done
    ;;
  rpi_hub|hub)
    echo "Deploying lua build for raspberry_pi hub..."
    # for file in ./rpi_hub
    # do
    #   echo "something something batman"
    # done
    ;;
  *)
    echo $"Usage: $0 {door_sensor|hub}"
    exit 1
esac
